import 'package:flutter/material.dart';

import '../../../core/core.dart';

/// Sélecteur d'emoji, ouvert depuis la barre de saisie.
///
/// **Une liste écrite à la main, et non un paquet.** Les paquets de sélecteur
/// d'emoji embarquent leur propre police et leur propre catalogue — c'est-à-dire
/// une seconde source de vérité pour un rendu que `NotoColorEmoji` assure déjà.
/// Ce qu'il faut ici tient dans une liste : quelques centaines d'emojis, rangés
/// par famille.
///
/// Le catalogue est volontairement **court**. Un sélecteur complet compte plus
/// de trois mille glyphes et demande une recherche pour être utilisable ; celui
/// qu'on ouvre dans une conversation de famille sert à répondre vite. Le
/// clavier du système reste là pour le reste, et c'est lui qui a la recherche.
class EmojiPicker extends StatefulWidget {
  const EmojiPicker({super.key, required this.onSelected});

  final ValueChanged<String> onSelected;

  /// Hauteur du panneau. Assez pour deux familles visibles d'un coup, assez
  /// peu pour laisser voir les derniers messages au-dessus.
  static const double hauteur = 260;

  @override
  State<EmojiPicker> createState() => _EmojiPickerState();
}

class _EmojiPickerState extends State<EmojiPicker> {
  int _famille = 0;

  @override
  Widget build(BuildContext context) {
    final FamilleEmoji famille = famillesEmoji[_famille];

    return Container(
      height: EmojiPicker.hauteur,
      decoration: BoxDecoration(
        color: context.couleurs.surface,
        border: Border(top: BorderSide(color: context.couleurs.border)),
      ),
      child: Column(
        children: <Widget>[
          SizedBox(
            height: 44,
            child: ListView.builder(
              scrollDirection: Axis.horizontal,
              padding: const EdgeInsets.symmetric(horizontal: AppSpacing.sm),
              itemCount: famillesEmoji.length,
              itemBuilder: (BuildContext context, int index) {
                final bool actif = index == _famille;
                return Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 2),
                  child: TextButton(
                    onPressed: () => setState(() => _famille = index),
                    style: TextButton.styleFrom(
                      minimumSize: const Size(44, 36),
                      padding: EdgeInsets.zero,
                      backgroundColor: actif
                          ? context.couleurs.primarySoft
                          : Colors.transparent,
                    ),
                    child: EmojiText(
                      famillesEmoji[index].onglet,
                      style: const TextStyle(fontSize: 20),
                    ),
                  ),
                );
              },
            ),
          ),
          Divider(height: 1, color: context.couleurs.border),
          Expanded(
            child: GridView.builder(
              padding: const EdgeInsets.all(AppSpacing.sm),
              gridDelegate: const SliverGridDelegateWithMaxCrossAxisExtent(
                maxCrossAxisExtent: 48,
                childAspectRatio: 1,
              ),
              itemCount: famille.emojis.length,
              itemBuilder: (BuildContext context, int index) {
                final String emoji = famille.emojis[index];
                return InkWell(
                  onTap: () => widget.onSelected(emoji),
                  borderRadius: AppRadii.fieldRadius,
                  child: Center(
                    child: EmojiText(
                      emoji,
                      style: const TextStyle(fontSize: 26),
                    ),
                  ),
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}

@immutable
class FamilleEmoji {
  const FamilleEmoji(this.onglet, this.emojis);

  /// L'emoji qui sert d'onglet : un mot y serait tronqué à 44 dp.
  final String onglet;
  final List<String> emojis;
}

/// Le catalogue, rangé comme un clavier : ce qu'on emploie le plus d'abord.
const List<FamilleEmoji> famillesEmoji = <FamilleEmoji>[
  FamilleEmoji('😀', <String>[
    '😀',
    '😃',
    '😄',
    '😁',
    '😆',
    '😅',
    '🤣',
    '😂',
    '🙂',
    '🙃',
    '😉',
    '😊',
    '😇',
    '🥰',
    '😍',
    '🤩',
    '😘',
    '😗',
    '😚',
    '😋',
    '😛',
    '🤪',
    '🤨',
    '🧐',
    '🤓',
    '😎',
    '🥳',
    '😏',
    '😒',
    '😞',
    '😔',
    '😟',
    '😕',
    '🙁',
    '😣',
    '😖',
    '😫',
    '😩',
    '🥺',
    '😢',
    '😭',
    '😤',
    '😠',
    '😡',
    '🤯',
    '😳',
    '🥵',
    '🥶',
    '😱',
    '😨',
    '😰',
    '😥',
    '😓',
    '🤗',
    '🤔',
    '🤭',
    '🤫',
    '😬',
    '🙄',
    '😴',
    '🤤',
    '😷',
    '🤒',
    '🤕',
    '🤢',
    '🤮',
    '🥴',
    '😵',
    '🤠',
    '😈',
  ]),
  FamilleEmoji('👍', <String>[
    '👍',
    '👎',
    '👌',
    '🤌',
    '✌️',
    '🤞',
    '🤟',
    '🤘',
    '🤙',
    '👈',
    '👉',
    '👆',
    '👇',
    '☝️',
    '✋',
    '🤚',
    '🖐️',
    '🖖',
    '👋',
    '🤝',
    '🙏',
    '✍️',
    '💪',
    '🦾',
    '👏',
    '🙌',
    '👐',
    '🤲',
    '🫶',
    '❤️',
    '🧡',
    '💛',
    '💚',
    '💙',
    '💜',
    '🖤',
    '🤍',
    '🤎',
    '💔',
    '❣️',
    '💕',
    '💞',
    '💓',
    '💗',
    '💖',
    '💘',
    '💝',
    '✨',
    '⭐',
    '🌟',
    '💫',
    '🔥',
    '💯',
    '💥',
    '🎉',
    '🎊',
    '🎈',
    '🎁',
    '🏆',
    '🥇',
  ]),
  FamilleEmoji('🍕', <String>[
    '🍏',
    '🍎',
    '🍐',
    '🍊',
    '🍋',
    '🍌',
    '🍉',
    '🍇',
    '🍓',
    '🫐',
    '🍒',
    '🍑',
    '🥭',
    '🍍',
    '🥥',
    '🥝',
    '🍅',
    '🥑',
    '🍆',
    '🥔',
    '🥕',
    '🌽',
    '🌶️',
    '🥒',
    '🥬',
    '🥦',
    '🧄',
    '🧅',
    '🍄',
    '🥜',
    '🍞',
    '🥐',
    '🥖',
    '🥨',
    '🧀',
    '🥚',
    '🍳',
    '🧈',
    '🥞',
    '🧇',
    '🥓',
    '🍔',
    '🍟',
    '🍕',
    '🌭',
    '🥪',
    '🌮',
    '🌯',
    '🥙',
    '🧆',
    '🥗',
    '🍝',
    '🍜',
    '🍲',
    '🍣',
    '🍱',
    '🍚',
    '🍰',
    '🎂',
    '🍫',
    '🍬',
    '🍭',
    '🍦',
    '☕',
    '🍵',
    '🥤',
    '🍺',
    '🍻',
    '🥂',
    '🍷',
  ]),
  FamilleEmoji('⚽', <String>[
    '⚽',
    '🏀',
    '🏈',
    '⚾',
    '🎾',
    '🏐',
    '🏉',
    '🎱',
    '🏓',
    '🏸',
    '🥅',
    '⛳',
    '🏹',
    '🎣',
    '🤿',
    '🥊',
    '🥋',
    '🛹',
    '🛼',
    '⛸️',
    '🎿',
    '⛷️',
    '🏂',
    '🏋️',
    '🤸',
    '🤺',
    '🤾',
    '🏌️',
    '🏇',
    '🧘',
    '🏄',
    '🏊',
    '🤽',
    '🚣',
    '🧗',
    '🚴',
    '🚵',
    '🎯',
    '🎮',
    '🎲',
    '🧩',
    '🎨',
    '🎭',
    '🎤',
    '🎧',
    '🎸',
    '🎹',
    '🥁',
    '🎺',
    '🎬',
  ]),
  FamilleEmoji('🚗', <String>[
    '🚗',
    '🚕',
    '🚙',
    '🚌',
    '🚎',
    '🏎️',
    '🚓',
    '🚑',
    '🚒',
    '🚐',
    '🚚',
    '🚛',
    '🚜',
    '🛵',
    '🏍️',
    '🚲',
    '🛴',
    '✈️',
    '🚀',
    '🛸',
    '🚁',
    '⛵',
    '🚤',
    '🛳️',
    '⚓',
    '🚂',
    '🚆',
    '🚇',
    '🗺️',
    '🏔️',
    '⛰️',
    '🌋',
    '🏕️',
    '🏖️',
    '🏝️',
    '🏜️',
    '🌅',
    '🌄',
    '🌈',
    '☀️',
    '🌤️',
    '⛅',
    '🌧️',
    '⛈️',
    '❄️',
    '⛄',
    '🌊',
    '🏠',
    '🏡',
    '🏢',
  ]),
  FamilleEmoji('✅', <String>[
    '✅',
    '☑️',
    '✔️',
    '❌',
    '❎',
    '➕',
    '➖',
    '❓',
    '❗',
    '‼️',
    '⚠️',
    '🔔',
    '🔕',
    '📅',
    '📆',
    '⏰',
    '⏳',
    '📌',
    '📎',
    '🔗',
    '📝',
    '📄',
    '📊',
    '📈',
    '📉',
    '💰',
    '💳',
    '🛒',
    '🎓',
    '💼',
    '🔑',
    '🔒',
    '🔓',
    '💡',
    '🔦',
    '🔍',
    '📷',
    '📱',
    '💻',
    '🖥️',
  ]),
];
